include $(GOROOT)/src/Make.inc

TARG=puclient
GOFILES=\
		main.go\
		engine.go\
		image.go\
		font.go\
		color.go\
		rect.go\
		game.go\
		login.go\
		connection.go\
		gameprotocol.go\
		networkconst.go\
		gui/gui.go\
		gui/gui_const.go\
		gui/element.go\
		gui/textfield.go\
		messages/login.go\

include $(GOROOT)/src/Make.cmd
