include $(GOROOT)/src/Make.inc

TARG=puclient
GOFILES=\
		main.go\
		engine.go\
		image.go\
		font.go\
		color.go\
		rect.go\
		game.go\
		gui/gui.go\
		gui/gui_const.go\
		gui/textfield.go\

include $(GOROOT)/src/Make.cmd
