include $(GOROOT)/src/Make.inc

TARG=puclient
GOFILES=\
		main.go\
		engine.go\
		image.go\
		font.go\
		color.go\
		rect.go\
		game.go\
		gameimages.go\
		login.go\
		connection.go\
		gameprotocol.go\
		networkconst.go\
		map.go\
		tile.go\
		layer.go\
		creature.go\
		player.go\
		gui/gui.go\
		gui/gui_const.go\
		gui/element.go\
		gui/textfield.go\
		gui/listbox.go\
		gui/scrollbar.go\
		messages/login.go\
		messages/identity.go\
		messages/tiles.go\
		messages/walk.go\
		messages/ping.go\
		messages/warp.go\
		messages/turn.go\

include $(GOROOT)/src/Make.cmd
