# Copyright 2009 The Go Authors.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=puserver
GOFILES=\
	main.go\
	uniqueid.go\
	server.go\
	game.go\
	connection.go\
	protocollogin.go\
	creature.go\
	player.go\
	tile.go\
	messages/loginmessage.go\

include $(GOROOT)/src/Make.cmd
