/*Pokemon Universe MMORPG
Copyright (C) 2010 the Pokemon Universe Authors

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.*/
package main

const (
	GENDER_NEUTRAL int = iota
	GENDER_MALE
	GENDER_FEMALE
)

const (
	_ int = iota
	TYPE_NORMAL
	TYPE_FIGHTING
	TYPE_FLYING
	TYPE_POISON
	TYPE_GROUND
	TYPE_ROCK
	TYPE_BUG
	TYPE_GHOST
	TYPE_STEEL
	TYPE_FIRE
	TYPE_WATER
	TYPE_GRASS
	TYPE_ELECTRIC
	TYPE_PSYCHIC
	TYPE_ICE
	TYPE_DRAGON
	TYPE_DARK
	TYPE_UNKNOWN
)

const (
	STATUS_FINE int = 0
	STATUS_PARALYSED = 1
	STATUS_ASLEEP = 2
	STATUS_FROZEN = 3
	STATUS_BURNT = 4
	STATUS_POISONED = 5
	STATUS_CONFUSED = 6
	STATUS_ATTRACTED = 7
	STATUS_WRAPPED = 8
	STATUS_NIGHTMARED = 9
	STATUS_TORMENTED = 12
	STATUS_DISABLED = 13
	STATUS_DROWSY = 14
	STATUS_HEALBLOCKED = 15
	STATUS_SLEUTHED = 17
	STATUS_SEEDED = 18
	STATUS_EMBARGOED = 19
	STATUS_REQUIEMED = 20
	STATUS_ROOTED = 21
	STATUS_KEOD = 31
)

const (
	STATUSFEELING_FEELCONFUSION int = iota
	STATUSFEELING_HURTCONFUSION
	STATUSFEELING_FREECONFUSION
	STATUSFEELING_PREVPARALYSED
	STATUSFEELING_PREVFROZEN
	STATUSFEELING_FREEFROZEN
	STATUSFEELING_FEELASLEEP
	STATUSFEELING_FREEASLEEP
	STATUSFEELING_HURTBURN
	STATUSFEELING_HURTPOISON
)

const (
	GENDERAVAIL_NEUTRALAVAIL int = iota
	GENDERAVAIL_MALEAVAIL
	GENDERAVAIL_FEMALEAVAIL
	GENDERAVAIL_MALEANDFEMALEAVAIL
)

const (
	NATURE_HARDY int = iota
	NATURE_LONELY
	NATURE_BRAVE
	NATURE_ADAMANT
	NATURE_NAUGHTY
	NATURE_BOLD
	NATURE_DOCILE
	NATURE_RELAXED
	NATURE_IMPISH
	NATURE_LAX
	NATURE_TIMID
	NATURE_HASTY
	NATURE_SERIOUS
	NATURE_JOLLY
	NATURE_NAIVE
	NATURE_MODEST
	NATURE_MILD
	NATURE_QUIET
	NATURE_BASHFUL
	NATURE_RASH
	NATURE_CALM
	NATURE_GENTLE
	NATURE_SASSY
	NATURE_CAREFUL
	NATURE_QUIRKY
)

const (
	STAT_HP string = ""
	STAT_ATTACK = "Attack"
	STAT_DEFENSE = "Defense"
	STAT_SPATTACK = "Special Attack"
	STAT_SPDEFENSE = "Special Defense"
	STAT_SPEED = "Speed"
	STAT_ACCURACY = "Accuracy"
	STAT_EVASION = "Evasion"
	STAT_ALLSTATS = ""
)

const (
	WEATHER_NORMALWEATHER int = iota
	WEATHER_HAIL
	WEATHER_RAIN
	WEATHER_SANDSTORM
	WEATHER_SUNNY
)

const (
	WEATHERSTATE_CONTINUEWEATHER int = iota
	WEATHERSTATE_ENDWEATHER
	WEATHERSTATE_HURTWEATHER
)